### ISSUE TITLE
Error: Operation not permitted

### ISSUE THREAD

**Issue by tskimmett** [HardikModha/vscode-create-tests#10]
Clicking the `Create test file` menu item does not create a test file, and displays this error
![image](https://user-images.githubusercontent.com/4603206/56758079-b8b7fe80-6763-11e9-83e9-659d39a023f9.png)

**Comment by hardikmodha** [comment]
Looks like some sort of permissions issue. Can you make sure that the directory in which you are trying to create a file has appropriate permissions?

**Comment by hardikmodha** [comment]
Closing this for now. Let me know if there are any other issues.
