### ISSUE TITLE
Any way to make test file next to module?

### ISSUE THREAD

**Issue by wolverineks** [HardikModha/vscode-create-tests#5]
I want to put the test files next to the file they are testing, not in a subdirectory
I tried a bunch of settings but I couldn't get them created in the right spot

Are there settings that can do this?

```
foo.js
foo.test.js
src/
  bar.js
  bar.test.js
```

**Comment by hardikmodha** [comment]
@wolverineks, As of now there is no option to put the tests next to the file. However, It can be implemented easily if I mark the `testDirectoryName` as optional. What I am thinking is, If the user doesn't provide the `testDirectoryName` configuration value i.e. provides an empty string, it won't create the directory and keep the test file next to the actual file. Does that make sense?

**Comment by wolverineks** [comment]
Sounds good
Thanks!

**Comment by hardikmodha** [comment]
Cool. Thanks. I'll make the required changes for it and will release it in the next minor release. :)

**Comment by hardikmodha** [comment]
@wolverineks Published as [v1.1.0](https://github.com/HardikModha/vscode-create-tests/releases/tag/v1.1.0). Thanks for suggesting this and helping me improve the `vscode-create-tests`.
